# Generated by Django 4.1.7 on 2023-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128)),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
