# Generated by Django 4.1.7 on 2023-03-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_collector_carton_alter_collector_glass_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='garbagedelivery',
            table='Garbage deliveries',
        ),
    ]
