# Generated by Django 4.1.7 on 2023-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collector_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
